Update IG publish workflow to use IGSource repository and improve organization detection script

diff --git a/.azure-pipelines/ig-publish.yaml b/.azure-pipelines/ig-publish.yaml
--- a/.azure-pipelines/ig-publish.yaml
+++ b/.azure-pipelines/ig-publish.yaml
@@ -7,6 +7,10 @@ resources:
       type: git
       ref: refs/heads/task/el/build-agent
       endpoint: cross-project-connection
+    - repository: IGSource
+      type: github
+      name: servicewell/servicewell.fhir.wof-portal
+      endpoint: IG Github Connection
 
 pool:
   name: 'Implementation Guide Build Pool'
@@ -14,11 +18,15 @@ pool:
 jobs:
   - job: SetupPublish
     steps:
-      - checkout: self
+      - checkout: IGSource
         persistCredentials: true
 
       - script: |
-          ORG=$(yq '.id' /azp/_work/1/s/sushi-config.yaml | cut -d'.' -f1)
+          ORG=$(awk -F': *' '/^id:/{print $2; exit}' $(Build.SourcesDirectory)/sushi-config.yaml | cut -d'.' -f1)
+          if [ -z "$ORG" ]; then
+            echo "Unable to detect organization from sushi-config.yaml id" >&2
+            exit 1
+          fi
           echo "##vso[task.setvariable variable=org]$ORG"
         displayName: Detect organization from sushi-config
 
